application: gogistics-tw
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/javascript

- url: /img
  static_dir: static/images

- url: /
  script: dispatchers.index_dispatcher.app

inbound_services:
- channel_presence

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
