application: gogistics-tw
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /bisque
  static_dir: static/bisque_font_style

- url: /font_styles/(.*\.(ttf|otf|tcc))$
  static_files: static/font_styles/\1
  upload: static/font_styles/(.*\.(ttf|otf|tcc))$
  mime_type: application/x-font-otf

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/javascripts

- url: /leaflet
  static_dir: static/leaflet-0.6.4

- url: /img
  static_dir: static/images

- url: /mis
  static_dir: static/mis

- url: /(index_.*)?
  script: dispatchers.dispatchers_index.app

- url: /cron_tasks_.*
  script: dispatchers.dispatchers_cron_tasks.app
  login: admin

- url: /gcm_.*
  script: dispatchers.dispatchers_gcm.app

- url: /demos/.*
  script: dispatchers.dispatchers_demos.app

builtins:
- remote_api: on

inbound_services:
- channel_presence
- warmup

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest

