application: app-enjoy
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(base/.*)?
  script: dispatchers.dispatchers_base.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest