application: gogistics-rtc
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /img
  static_dir: static/images

- url: /js
  static_dir: static/javascripts

- url: /css
  static_dir: static/css

- url: /mis
  static_dir: static/mis

- url: /.*
  script: apprtc.app


inbound_services:
- channel_presence

libraries:
- name: jinja2
  version: latest
